replicaCount: 1

image:
  repository: 13.48.106.244/smart-task-management-system/api-gateway
  tag: v1
  pullPolicy: Always

imagePullSecrets: []

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

containerPort: 5000

resources: {}

env:
  PORT: "5000"
  JWT_SECRET: "mysecretkey"
  MONGO_URI: "mongodb://mongodb:27017/taskdb"
  AUTH_SERVICE_URL: "http://auth-service-auth-service:5001"
  TASK_SERVICE_URL: "http://task-service-task-service:5002"
  NOTIFICATION_SERVICE_URL: "http://notification-service-notification-service:5003"
  REPORT_SERVICE_URL: "http://report-service-report-service:5004"

ingress:
  enabled: true
  className: nginx
  host: api.smarttask.local
  path: /
  pathType: Prefix
  tls: false


